# ==========================================
# CONFIGURACIÓN GENERAL
# ==========================================
STACK_NAME="DEPLOYMENT_TRACKER"

# Imágenes base (sin versión)
export IMG_APP="despliegues"
export IMG_DB="mysql"

# Hostnames internos (opcional)
export HOST_APP="deployment-tracker-app"
export HOST_DB="deployment-tracker-db"

SERVICIOS_A_PROCESAR=("IMG_APP" "IMG_DB")

# ==========================================
# RED (siempre externa en Swarm)
# ==========================================
PREPROD_NETWORK="proxy_redarco_swarm"
PROD_NETWORK="proxy_redarco_swarm"

# ==========================================
# VARIABLES DE APP (sin .env)
# ==========================================
# Base de datos
export DB_NAME="deployment_tracker"
export DB_USER="arco"
export DB_PASSWORD="gYlrmd75M%7Px7"
export DB_ROOT_PASSWORD="gZf%J6ilJtlAVb"

# App
export NEXT_PUBLIC_SITE_URL="http://localhost:3000"
